# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Diet.destroy_all 
User.destroy_all
Workout.destroy_all
Goal.destroy_all 


keto = Diet.create(name: "Ketogenic", description: "A Ketogenic lifestyle is a very low carb, high fat diet that shares many similarities with the Atkins and low carb diets. It involves drastically reducing carbohydrate intake and replacing it with fat. This reduction in carbs puts your body into a metabolic state called ketosis, which becomes a fat burning machine.", restriction: "No sugar and your daily intake of carbohydrates should be less than 50 grams a day ", calorie: 0 , water: 0 )
paleo = Diet.create(name: "Paleolithic", description: "A Paleolithic lifestyle is based upon the premise of consuming only those foods available during the Paleolithic era (also known as the Stone Age). People at this time were hunter-gatherers, meaning that all animals were hunted and plants were gathered from nature.", restriction: "Processed foods, sugar, soft drinks, grains, most dairy products, legumes, artificial sweeteners, vegetable oils, margarine and trans fats.", calorie: 0 , water: 0)
clean = Diet.create(name: "Low Fat", description: "A Low Fat lifestyle is one that restricts fat, and often saturated fat and cholesterol as well. Low-fat diets are intended to reduce the occurrence of conditions such as heart disease and obesity. Fat carries a higher number of calories per gram than carbohydrates or proteins and so reducing fat can help to reduce your overall calorie intake. Whole grain versions of foods such as bread are recommended in preference to non-whole grain versions (such as white bread) partly because they are turned into blood sugar more slowly. The fibre and extra nutrients they contain are also healthier than white versions. It is recommended to include a significant proportion of fruit and vegetables through each day.", restriction: " Limit saturated fat to less than 7% of your total daily calories. Avoid trans fat as much as possible, which is typically used in fried and baked foods. ", calorie: 0 , water: 0 )
plant = Diet.create(name: "Plant Based", description: "A Plant-Based or Plant-Forward eating pattern focuses on foods primarily from plants. This includes not only fruits and vegetables, but also nuts, seeds, oils, whole grains, legumes, and beans. It doesn’t mean that you are vegetarian or vegan and never eat meat or dairy. Rather, you are proportionately choosing more of your foods from plant sources.", restriction: "Try to avoid fast food, desserts and sweetened beverages, packaged foods and processed meats.", calorie: 0 , water: 0 )
protein = Diet.create(name: "High Protein", description: "A High-Protein lifestyle encourages eating more protein and fewer carbohydrates or fat to boost weight loss, improve energy, and enhance athletic performance. Protein is an essential nutrient for health and is responsible for a number of important functions in the body, including hormones, enzymes, and cell repair and maintenance. In general, a high-protein diet recommends getting more than 20% of your total calories from protein.", restriction: "Eat less refined carbohydrates, such as bread, pasta and white rice, saturated fats and sugar.", calorie: 0 , water: 0)


cycling = Workout.create(name: "Cycling", description: "Cycling is a great exercise to help you lose weight and great for people of all fitness levels, which can be done outdoors on a bicycle or indoors on a stationary bike. It has been linked to various health benefits, including increased insulin sensitivity and a reduced risk of certain chronic diseases. ", detail: "Aim to cycle for 30 -60 minutes, 4-6 times per week at a moderate speed level. ", video: "ttps://www.youtube.com/watch?v=x4WHeVf5DN4", image: "https://static.euronews.com/articles/stories/04/96/92/54/945x531_cmsv2_46d24b9b-1eec-58cf-ad75-cc31ea0a204d-4969254.jpg" )
jogging = Workout.create(name: "Jogging", description: "Jogging is a great exercise to help you lose weight. Jogging helps build strong bones, strengthen muscles and improve cardiovascular fitness. If you find jogging outdoors to be hard on your joints, try jogging on softer surfaces like grass. Also, many treadmills have built-in cushioning, which may be easier on your joints. ", detail: "Aim to jog for 45-60 minutes, 3-4 times per week.", video: "https://www.youtube.com/watch?v=brFHyOtTwH4", image: "https://cdn.cdnparenting.com/articles/2019/01/21120025/1195922569-H.jpg")
hiit = Workout.create(name: "High- Intensity Interval Training (HIIT) ", description: "Interval training refers to short burst of intense exercise that alternate with recovery periods. It is an effective weight loss strategy that can be applied to many types of exercises, including running, jumping, biking and more. All you need to do is choose a type of exercise, such as running, jumping, or biking, and your exercise and rest times. ", detail: "Aim to have a high-intensity interval training workout for 45-60 minutes, 3-4 times per week. ", video: " https://www.youtube.com/watch?v=1YrKGvgwJE8", image: " https://purlifefitness.com/wp-content/uploads/2016/09/HIIT-Training.jpg")
swimming = Workout.create(name: "Swimming", description: "Swimming is a fun way to lose weight and get in shape. Swimming is a great low-impact exercise, meaning that it’s easier on your joints. This makes it a great option for people who have injuries or joint pain. It may help improve your flexibility and reduce risk factors for various diseases.", detail: "Aim to swim for 30 minutes, 3 times per week.", video: "https://www.youtube.com/watch?v=nlGsZTsZaFc", image: "https://res.cloudinary.com/grohealth/image/upload/$wpsize_!_cld_full!,w_2560,h_1920,c_scale/v1588106919/action-athlete-blue-863988-scaled.jpg")
walking = Workout.create(name: "Walking", description: "A convenient and an easy way for beginners to start exercising without feeling overwhelmed or needing to purchase equipment. It's also a lower-impact exercise, meaning it doesn’t stress your joints. You can gradually increase the duration or frequency of your walks as you become more fit.", detail: "Aim to walk for 30 minutes, 3-4 times a week. ", video: "https://www.youtube.com/watch?v=3Ka7B3hCg08&t=215s", image: "https://contents.mediadecathlon.com/p1261690/1920x0/9cr4/marche-sportive.jpg?k=d4381cc8c4da7fc4eb78433760ac5a36")
bench_press = Workout.create(name: "Bench Press", description: "Lie flat on a bench, holding a bar with a shoulder-width grip. Plant your feet on the floor and tense your muscles. Lower the bar until it touches your chest, then press it back up powerfully.", detail: "Sets: 5 Reps: 8 Rest: 60 seconds", video: "https://www.youtube.com/watch?v=gRVjAtPip0Y", image: "https://cdn2.coachmag.co.uk/sites/coachmag/files/styles/insert_main_wide_image/public/2018/04/bench-press.jpg?itok=3xrSG37z")
lat_pull_down = Workout.create(name: "Lat Pull-Down", description: "Position yourself at the machine with a shoulder-width overhand grip on the bar. Keeping your chest up and abs braced, pull the bar down, leading with your elbows. Hold the bottom position for a second, then return to the start.", detail: "Sets: 5 Reps: 8 Rest: 60 seconds", video: "https://www.youtube.com/watch?v=yer9aNIe_V8", image: "https://cdn1.coachmag.co.uk/sites/coachmag/files/styles/insert_main_wide_image/public/2018/04/lat-pull-down.jpg?itok=ePNDnxfw")
cable_cross_over = Workout.create(name: "Cable Cross-Over", description: "Stand tall in the middle of a cable machine, holding a D-handle in each hand attached to the high pulley. Keeping your chest up and core braced, bring your hands down in a smooth arc to meet in front of your body. Hold for a second, then return to the start.", detail: "Sets: 4 Reps: 12 Rest: 60 seconds", video: "https://www.youtube.com/watch?v=taI4XduLpTk", image: "https://cdn2.coachmag.co.uk/sites/coachmag/files/styles/insert_main_wide_image/public/2018/06/cable-cross-over.jpg?itok=G0G3PZnH")
cable_straigth_arm_pull_down = Workout.create(name: "Cable Straight-Arm Pull-Down", description: "Stand tall, facing the cable machine and holding a straight bar handle with both hands. Keeping your arms straight, pull the bar down towards your thighs in a smooth arc. Pause at the bottom, then reverse the movement back to the start. ", detail: "Sets: 4 Reps: 12 Rest: 60 seconds", video: "https://www.youtube.com/watch?v=wcVDItawocI", image: "https://cdn1.coachmag.co.uk/sites/coachmag/files/styles/insert_main_wide_image/public/2018/04/cable-triceps-press-down.jpg?itok=SdvnPDdS")
incline_dumbbell_shoulder_press = Workout.create(name: "Incline Dumbbell Shoulder Press", description: "Lie back on an incline bench, holding a dumbbell in each hand at chest height. Plant your feet on the floor and get your body tight. Press the weights straight up so your arms are straight, then lower them under control. ", detail: "Sets: 4 Reps: 12 Rest: 30 seconds", video: "https://www.youtube.com/watch?v=0G2_XV7slIg", image: "https://cdn1.coachmag.co.uk/sites/coachmag/files/styles/insert_main_wide_image/public/2018/05/incline-dumbbell-shoulder-press.jpg?itok=G2Joyx5u")
prone_dumbbell_row = Workout.create(name: "Prone Dumbbell Row ", description: "Lie chest-down on an incline bench, holding a dumbbell in each hand. Keeping your chest against the bench, row the weights up, leading with your elbows. Hold the top position for a second, then lower the weights back to the start. ", detail: "Sets: 4 Reps: 12 Rest: 60 seconds", video: "https://www.youtube.com/watch?v=2LxN3_3atps", image: "https://cdn1.coachmag.co.uk/sites/coachmag/files/styles/insert_main_wide_image/public/2018/05/prone-dumbbell-row.jpg?itok=0zhESdMB")
back_squat = Workout.create(name: "Back Squat ", description: "Stand tall, holding a bar across the back of your shoulders. Keeping your chest up and your whole body tight, bend your knees to squat down as low as you can but don’t let your knees roll inwards. Push through your heels to stand back up.", detail: "Sets: 5 Reps: 8 Rest: 60 seconds", video: "https://www.youtube.com/watch?v=Uv_DKDl7EjA", image: "https://cdn2.coachmag.co.uk/sites/coachmag/files/styles/insert_main_wide_image/public/2018/04/back-squat.jpg?itok=JUgzKbsh")
overhead_press= Workout.create(name: "Overhead Press", description: "Stand tall, holding a bar across the front of your chest with an overhand grip. Keeping your chest up and core engaged, press the bar directly overhead so your arms are straight. Lower it under control to return to the start. ", detail: "Sets: 5 Reps: 8 Rest: 60 seconds", video: "https://www.youtube.com/watch?v=QAQ64hK4Xxs", image: "https://cdn1.coachmag.co.uk/sites/coachmag/files/styles/insert_main_wide_image/public/2018/05/overhead-press.jpg?itok=7XO1zJOj")
leg_extension = Workout.create(name: "Leg Extension", description: "Position yourself correctly on the machine with the padded bar against the bottom of your shins. Keeping you upper body tight, raise your feet to straighten your lets. Pause at the top with your quads engaged, then return to the start. ", detail: "Sets: 4 Reps: 12 Rest: 60 seconds", video: "https://www.youtube.com/watch?v=1DlLe1r0i74", image: "https://cdn2.coachmag.co.uk/sites/coachmag/files/styles/insert_main_wide_image/public/2018/04/leg-extension.jpg?itok=fOgvzIec")
hamstring_curl = Workout.create(name: "Hamstring Curl", description: "Position yourself correctly on the machine with the padded bar against the back of your lower legs. Keeping your upper body tight, push your feet down to bend your legs. Pause at the top with your hamstrings engaged, then return to the start.", detail: "Sets: 4 Reps: 12 Rest: 60 seconds", video: "https://www.youtube.com/watch?v=F488k67BTNo", image: "https://cdn1.coachmag.co.uk/sites/coachmag/files/styles/insert_main_wide_image/public/2018/04/hamstring-curl.jpg?itok=mKHSVWUz")
seated_dumbbell_overhead = Workout.create(name: "Seated Dumbbell Overhead Press	", description: "Sit on an upright bench, holding a dumbbell in each hand at shoulder height. Keeping your chest up and core braced, press the weights directly overhead so your arms are straight. Slowly lower back to the start. ", detail: "Sets: 4 Reps: 12 Rest: 30 seconds", video: "https://www.youtube.com/watch?v=lfb3ffbrd4Q", image: "https://cdn1.coachmag.co.uk/sites/coachmag/files/styles/insert_main_wide_image/public/2018/04/seated-dumbbell-overhead-press.jpg?itok=7_OezRzg")
seated_dumbbell_lateral = Workout.create(name: "Seated Dumbbell Lateral Raise ", description: "Sit on an upright bench, holding a light dumbbell in each hand by your sides with a slight bend in your elbows. Keeping your chest up and core braced, raise the weights out to shoulder height, leading with your elbows, then return slowly to the start. ", detail: "Sets: 4 Reps: 12 Rest: 60 seconds", video: "https://www.youtube.com/watch?v=3zohLHTjFH0", image: "https://cdn2.coachmag.co.uk/sites/coachmag/files/styles/insert_main_wide_image/public/2018/04/seated-dumbbell-lateral-raise.jpg?itok=Jyfss-a4")
drips = Workout.create(name: "Tricep Dips", description: "Grip parallel bars with straight arms and your legs crossed behind you. Keeping your chest up and core braced, lower your body by bending your elbows until they’re at 90°. Press back up to return to the start. ", detail: "Sets: 5 Reps: 8 Rest: 60 seconds", video: "https://www.youtube.com/watch?v=yN6Q1UI_xkE", image: "https://cdn1.coachmag.co.uk/sites/coachmag/files/styles/insert_main_wide_image/public/2018/04/triceps-dip.jpg?itok=YrpmAQbH")
under_lat_pull_down = Workout.create(name: "Underhand Lat Pull-Down", description: "Position yourself at the machine with a narrow underhand grip on the bar. Keeping your chest up and abs braced, pull the bar down, leading with your elbows. Hold the bottom position for a second, then return to the start. ", detail: "Sets: 5 Reps: 8 Rest: 60 seconds", video: "https://www.youtube.com/watch?v=PPVJb5d1nWY", image: "https://cdn1.coachmag.co.uk/sites/coachmag/files/styles/insert_main_wide_image/public/2018/04/underhand-lat-pull-down.jpg?itok=GcOU1Sje")
seated_cable_row = Workout.create(name: "Seated Cable Row", description: "Sit on the machine, holding a double- grip cable attachment in both hands. Keeping your chest up, row your hands in towards your body, leading with your elbows. Pause, then return to the start. ", detail: "Sets: 4 Reps: 12 Rest: 60 seconds", video: "https://www.youtube.com/watch?v=4mRy8U542Fo", image: "https://cdn2.coachmag.co.uk/sites/coachmag/files/styles/insert_main_wide_image/public/2018/05/seated-cable-row.jpg?itok=1gFQCL9Y")
incline_dumbbell_curl = Workout.create(name: "Incline dumbbell biceps curl", description: "Lie back on an incline bench, holding a dumbbell in each hand with your palms facing forwards and elbows tight to your sides. Keeping your elbows there, curl the weights up to shoulder height. Squeeze your biceps at the top, then lower the weights. ", detail: "Sets: 4 Reps: 12 Rest: 60 seconds", video: "https://www.youtube.com/watch?v=MVSccftvAQw", image: "https://cdn2.coachmag.co.uk/sites/coachmag/files/styles/insert_main_wide_image/public/2018/06/incline-biceps-curl.jpg?itok=Tb5hWCfQ")
cable_curl = Workout.create(name: "Cable Bicep Curl ", description: "Stand tall facing a cable machine, holding a straight bar handle with both hands. Keeping your chest up, pull the bar down towards your thighs in a smooth arc. Pause at the bottom, then reverse the movement back to the start. ", detail: "Sets: 4 Reps: 12 Rest: 30 seconds", video: "https://www.youtube.com/watch?v=NFzTWp2qpiE", image: "https://cdn1.coachmag.co.uk/sites/coachmag/files/styles/insert_main_wide_image/public/2018/04/cable-biceps-curl.jpg?itok=rVaz0VAN")
cable_press_down = Workout.create(name: "Cable Triceps Press-Down", description: "Stand tall in front of a cable machine., holding a double-rope handle attached to the high pulley with palms facing. Keeping your chest up and elbows tight to your sides, press your hands down to straighten your arms, then slowly return to the start.", detail: "Sets: 4 Reps: 12 Rest: 60 seconds", video: "https://www.youtube.com/watch?v=8WL0m0vLAPo", image: "https://cdn1.coachmag.co.uk/sites/coachmag/files/styles/insert_main_wide_image/public/2018/04/cable-triceps-press-down.jpg?itok=SdvnPDdS")
incline_bench = Workout.create(name: "Incline Bench Press", description: " Lie back on an incline bench, holding a bar with a shoulder-width grip. Plant your feet on the floor and tense your muscles. Lower the bar until it touches your chest, then press it back up powerfully.", detail: "Sets: 5 Reps: 8 Rest: 60 seconds", video: "https://www.youtube.com/watch?v=jPLdzuHckI8", image: "https://cdn1.coachmag.co.uk/sites/coachmag/files/styles/insert_main_wide_image/public/2018/05/incline-bench-press.jpg?itok=6VVsGPRe")
dumbbell_pull_over = Workout.create(name: "Dumbbell Pull-Over", description: "Lie on a flat bench holding a dumbbell with both hands above your chest with straight arms. Lower the weight under control behind your head, keeping your arms straight. Then raise it back to the start position. ", detail: "Sets: 5 Reps: 8 Rest: 60 seconds ", video: "https://www.youtube.com/watch?v=Q8l6ykgnmPM", image: "https://cdn1.coachmag.co.uk/sites/coachmag/files/styles/insert_main_wide_image/public/2018/04/dumbbell-pull-over_0.jpg?itok=IptHVNgA")
ez_bar = Workout.create(name: "EZ-Bar Upright Row", description: "Stand tall, holding an EZ-bar with a shoulder-width overhand grip. Keeping your chest up and core braced, row the bar up to chin height, leading with your elbows. Pause at the top, then lower the bar back to the start under control. ", detail: "Sets: 4 Reps: 12 Rest: 60 seconds", video: "https://www.youtube.com/watch?v=pNTPVN3FkSo", image: "https://cdn2.coachmag.co.uk/sites/coachmag/files/styles/insert_main_wide_image/public/2018/06/ez-bar-upright-row.jpg?itok=E4wrKQhj")
dumbbell_lateral_raise = Workout.create(name: "Dumbbell Lateral Raise ", description: "Stand tall holding a light dumbbell in each hand by your sides with a slight bend in your elbows. Keeping your chest up and core braced, raise the weights out the shoulder height, leading with your elbows, then return slowly to the start.", detail: "Sets: 4 Reps: 12 Rest: 60 seconds", video: "https://www.youtube.com/watch?v=b_LEX4n9lOs", image: "https://cdn2.coachmag.co.uk/sites/coachmag/files/styles/insert_main_wide_image/public/2018/06/lateral-raise.jpg?itok=wj_mWkwF")
incline_flye = Workout.create(name: "Incline Dumbbell Fly", description: "Lie back on an incline bench holding a dumbbell in each hand above your chest with a slight bend in your elbows. Lower the weights out to the sides under control, keeping that bend in your elbows, then return to the start position.", detail: "Sets: 4 Reps: 12 Rest: 30 seconds", video: "tps://www.youtube.com/watch?v=ajdFwa-qM98", image: "https://cdn1.coachmag.co.uk/sites/coachmag/files/styles/insert_main_wide_image/public/2018/04/incline-dumbbell-flye.jpg?itok=yg57-zpg")
push_up = Workout.create(name: "Push-up", description: "Get on all four with your legs and arms straight, your hands under your shoulder and your body in a straight line from head to heels. Engage your abs and bend your elbows to lower your chest towards the floor, then press back up powerfully. ", detail: "Sets: 4 Reps: 12 Rest: 60 seconds", video: "https://www.youtube.com/watch?v=IODxDxX7oi4", image: "https://cdn2.coachmag.co.uk/sites/coachmag/files/styles/insert_main_wide_image/public/2018/05/press-up.jpg?itok=9PeUWARv")
rest = Workout.create(name: "Rest Day", description: "Remeber to rest, A rest day allows your body to recover. Recovery reduces your risk of overuse injuries and stress fractures and allows your body to adapt to the training load. Rest days are essential to becoming a faster, stronger runner and achieving your goals. Rest days provide mental benefits as well", detail: "Aim to rest 3 times a week", video: "https://www.youtube.com/watch?v=IrYBQtbiaa8", image: "https://media1.popsugar-assets.com/files/thumbor/SfwoRebkd7XKl1QqFFk06CCkMVM/fit-in/2048xorig/filters:format_auto-!!-:strip_icc-!!-/2014/01/03/913/n/1922729/56329a000fa52ee1_78720949.jpg")
hiit_e = Workout.create(name: "High-Intensity Interval Training (HIIT)", description: "Interval training refers to short burst of intense exercise that alternate with recovery periods. It is an effective workout to build endurance. HIIT can be applied to many types of exercises, including running, jumping, biking and more. All you need to do is choose a type of exercise, such as running, jumping, or biking, and your exercise and rest times. ", detail: "Aim to have a High-intensity interval training for 45-60 minutes, 3-4 times per week.", video: "https://www.youtube.com/watch?v=1YrKGvgwJE8", image: "https://purlifefitness.com/wp-content/uploads/2016/09/HIIT-Training.jpg")
uphill = Workout.create(name: "Uphill Running", description: "Running on hills is a form of resistance training. This kind of training builds muscular endurance and muscle strength because the major muscles of the body must work harder to proper your body up a hill. Working at a more intense level places a higher demand on the heart and lungs, forcing them to also become stronger through training. ", detail: "Aim to have a 30sec sprints at a 5% to 10% incline. Rest with a jog down and repeat for 5 to 8 reps ", video: "https://www.youtube.com/watch?v=jmAYJlY2dbc", image: "https://miro.medium.com/max/700/1*sL2_VCyJ9DzQMIBJIwRGtQ.jpeg")
swimming_e = Workout.create(name: "Swimming ", description: "Swimming is a fun way to get in shape and build endurance. Swimming is a great low-impact exercise, meaning that it’s easier on your joints. This makes it a great option for people who have injuries or joint pain. It may help improve your flexibility and reduce risk factors for various diseases.", detail: "Aim to swim for 30 minutes, 3 times per week.", video: "https://www.youtube.com/watch?v=nlGsZTsZaFc", image: "https://res.cloudinary.com/grohealth/image/upload/$wpsize_!_cld_full!,w_2560,h_1920,c_scale/v1588106919/action-athlete-blue-863988-scaled.jpg")
long_distance = Workout.create(name: "Long Distance Running", description: "Long-distance running, or endurance running, is a form of continuous running over distance of at least 3km (1.9 mi). It helps develop greater aerobic endurance, strengthens your heart and open your capillaries, sending energy to working muscles and flushing waste projects from fatigues muscles.", detail: "Aim to run more then 45mins, 3 to 4 times per week.", video: "https://www.youtube.com/watch?v=6abu6QXAGEQ", image: "https://d3laewezlz9ul2.cloudfront.net/wp-content/uploads/2018/11/01152924/18279-choosing-running-shoes-right-cushion-blog-1200x675.jpg")
heavy = Workout.create(name: "Heavy Bag Workout", description: "Hitting a heavy bag is a great way to build endurance. Heavy bag workouts mix aerobic with anaerobic types of exercise. A person can gain improvements in every part of the upper body and lower body.", detail: "Aim to hit the bag 25 to 35 mins, 4 times per week", video: "https://www.youtube.com/watch?v=yQ0dopb69ns", image: "https://image.freepik.com/free-photo/sexy-asia-girl-punching-boxing-bag_39704-636.jpg")
cycling_e = Workout.create(name: "Cycling", description: "Cycling is a great exercise to help build endurance and great for people of all fitness levels, which can be done outdoors on a bicycle or indoors on a stationary bike. It has been linked to various health benefits, including increased insulin sensitivity and a reduced risk of certain chronic diseases. ", detail: " Aim to cycle for 30 -60 minutes, 4-6 times per week at a moderate speed level." , video: "https://www.youtube.com/watch?v=x4WHeVf5DN4", image: "https://static.euronews.com/articles/stories/04/96/92/54/945x531_cmsv2_46d24b9b-1eec-58cf-ad75-cc31ea0a204d-4969254.jpg")
kettlebell_goblet_squat = Workout.create(name: "Kettlebell Goblet Squat", description: "Hold the kettlebell with both hands in front of your chest, and squat down with your back straight and chest up. Descend until your elbows touch the insides of your knees, then put your weight on your heels as you stand back up.", detail: "Sets: 3 Reps: 10 Rest: 45 seconds", video: "https://www.youtube.com/watch?v=JiQboHyV9aE", image: "https://tonygentilcore.com/wp-content/uploads/2017/02/Goblet-squat.jpg")
back_squat_s = Workout.create(name: "Back Squat", description: "Hold the bar on your traps and stand with your feet roughly shoulder-width apart, toes pointing out slightly. Keep your back straight by looking at a spot on the floor about 2m in front of you, then sit back and down as if you’re aiming for a chair. Lower until your hip crease is below your knee. Keep your weight on your heels as you drive up.", detail: "Sets: 5 Reps: 5 Rest: 60-90 seconds", video: "https://www.youtube.com/watch?v=Uv_DKDl7EjA&t=8s", image: "https://cdn2.coachmag.co.uk/sites/coachmag/files/styles/insert_main_wide_image/public/2017/06/back-squat.jpg?itok=u2Qfxj9A")
bulgarian_split_squat = Workout.create(name: "Bulgarian Split Squat", description: "Start with your back foot on a bench and your front foot approximately 60cm in front of the bench, holding a dumbbell in each hand. Bend at the knee to lower towards the floor, keeping your torse upright, then press back up to the start. Make sure that your knee is in line with your ankle and that your front foot is far enough forwards that your knee doesn’t travel in front of your mid-foot. Complete all the reps on one side, then switch.", detail: "Sets: 2 Reps: 8 each side Rest: 60 seconds", video: "https://www.youtube.com/watch?v=JLEyaXRMv8o", image: "https://horizonpersonaltrainingnewingtonct.com/wp-content/uploads/2018/03/Bulgarian-Split-Squat-as-an-Alternative-to-the-Back-Squat.jpg")
snatch_grip_deadlift = Workout.create(name: "Snatch-Grip Deadlift", description: "Hold a barbell with your hands roughly double shoulder-width apart. Push through your heels and keep your chest up as you drive your hips forwards to lift the bar.", detail: "Sets: 3 Reps: 10 Rest: 60 seconds", video: "https://www.youtube.com/watch?v=NMDPXmGJI88", image: "https://cdn2.coachmag.co.uk/sites/coachmag/files/styles/insert_main_wide_image/public/2017/10/snatch-grip-deadlift.jpg?itok=GKdTWI5_")
kettlebell_swing = Workout.create(name: "Kettlebell swing", description: "Swing the kettlebell between your legs with both hands, then pop your hips forwards to drive it up to head height, keeping your arms relaxed. Let the bell swing back into the next rep and don’t bend your knees much.", detail: "Sets: 3 Reps: 10 Rest: 60 seconds", video: "https://www.youtube.com/watch?v=GYHbu2LRqD0", image: "https://i.pinimg.com/originals/04/af/c5/04afc521e78e78092b7741fe45a8a67e.jpg")
kettlebell_sumo_deadlift = Workout.create(name: "Kettlebell Sumo Deadlift", description: "Taking a wider stance than in a regular deadlift, place the kettlebell between your legs. Start the move by straightening your legs without changing the angle of your torse. Once your legs are straight, push your hips through to straighten up.", detail: "Sets: 3 Reps: 10 Rest: 60 seconds", video: "https://www.youtube.com/watch?v=4n4zj1S-Sxg", image: "https://az34g38t2tge2u2nadg77f6-wpengine.netdna-ssl.com/wp-content/uploads/2020/03/kettle-sumo-deadlift.jpg")
deadlift_s = Workout.create(name: "Deadlift", description: " Set up so you grip the bar with an overhand grip, hands just wider than shoulder-width apart. Initiate the movement by loading your hamstrings and straightening your knees. Once the bar is part your knees you can straighten up fully.", detail: "Sets: 5 Reps: 5 Rest: 60-90 seconds", video: "https://www.youtube.com/watch?v=ytGaGIn3SjE", image: "https://www.sci-mx.co.uk/wp-content/uploads/2018/07/How-to-deadlift.jpg")
romanian_deadlift =Workout.create(name: "Romanian Deadlift", description: "Hold a barbell with an overhand grip just outside your thighs. Hinge at the hips to send the bar down the front of your thighs, ensuring that the bar stays close to you throughout the lift. Lower until you feel a strong stretch in your hamstrings, then straighten back up, contracting your glutes at the top of the move. ", detail: "Sets: 4 Reps: 6-8 Rest 60-90sec", video: "https://www.youtube.com/watch?v=2SHsk9AzdjA", image: "https://nicktumminello.com/wp-content/uploads/2012/10/romanian-deadlift.jpg")
incline_bench_press_s = Workout.create(name: "Incline Bench Press", description: "Lie on a bench set at a 45° incline, holding a bar over your chest with your hands just wider than shoulder-width apart. Lower the bar until it’s touching your chest, then press it back up. ", detail: "Sets: 3 Reps: 10 Rest: 60 seconds", video: "https://www.youtube.com/watch?v=SrqOu55lrYU", image: "https://ast-ss.com/wp-content/uploads/2016/02/female-incline-bench-press.jpg")
push_up_s = Workout.create(name: "Push-Up", description: "Get on all four with your legs and arms straight, your hands under your shoulder and your body in a straight line from head to heels. Engage your abs and bend your elbows to lower your chest towards the floor, then press back up powerfully.", detail: "Sets: 3 Reps: To failure Rest: 60 seconds", video: "https://www.youtube.com/watch?v=IODxDxX7oi4", image: "https://cdn2.coachmag.co.uk/sites/coachmag/files/styles/insert_main_wide_image/public/2018/05/press-up.jpg?itok=9PeUWARv")
dumbbell_bench_press_s  = Workout.create(name: "Dumbbell Bench Press", description: "Lie on a bench with your feet on the floor directly underneath your knees. Hold the dumbbells above you with arms straight, then lower them to your chest. Then drive your feet hard into the floor and push the dumbbells back strongly to the start position.", detail: "Sets: 3 Reps: 10 Rest: 60 seconds", video: "https://www.youtube.com/watch?v=Y_7aHqXeCfQ", image: "https://cdn1.coachmag.co.uk/sites/coachmag/files/styles/insert_main_wide_image/public/2017/10/dumbbell-bench-press.jpg?itok=INr8h753")
bench_press_s = Workout.create(name: "Bench Press", description: "Grip the bar with hands slightly wider than shoulder-width apart and squeeze your lats together to create a pressing platform before you take the bar out of the rack. Watch the ceiling, not the bar, to ensure you’re pressing in the same line each time. Lower the bar to your chest, aiming to brush your T-shirt without bouncing. Press up powerfully, pause at the top, then do your next rep. ", detail: "Sets: 5 Reps: 5 Rest: 60-90 seconds", video: "https://www.youtube.com/watch?v=gRVjAtPip0Y&t=63s", image: "https://www.bodybuilding.com/images/2018/august/a-girls-gotta-bench-chest-workout-and-training-tips-header-960x540.jpg")
diamond_push_up =Workout.create(name: "Diamond Push-Up", description: "Get into a push up position, placing your hands close together so your thumbs and index fingers touch. Keeping your body in a straight line with your abs braced, lower until your chest is just above the floor, and then press back up.", detail: "Sets: 3 Reps: 8-10 Rest: 60 seconds ", video: "https://www.youtube.com/watch?v=8_ILkbB9an8Image", image: "https://cdn1.coachmag.co.uk/sites/coachmag/files/styles/insert_main_wide_image/public/2017/07/diamond-push-up-bradley-simmonds.jpg?itok=Ibq_sgDM")
front_squat_s = Workout.create(name: "Front Squat", description: "Take the bar out of the rack so it’s resting on the front of your shoulders and your palms face upwards. Squat down, keeping your chest up, then drive through your heels to stand.", detail: "Sets: 3 Reps: 10 Rest: 60 seconds", video: "https://www.youtube.com/watch?v=VfBOBhwXbro", image: "https://cdn1.coachmag.co.uk/sites/coachmag/files/styles/insert_main_wide_image/public/2017/10/front-squat_0.jpg?itok=7-VBZHqo")
dumbbell_jump_squat = Workout.create(name: "Dumbbell jump squat", description: "Stand with feet shoulder-width apart, holding a dumbbell in each hand. Squat down, then explode up to jump as high as you can. Land softly and go straight into the next rep.", detail: "Sets: 3 Reps: 5 Rest: 60 seconds", video: "https://www.youtube.com/watch?v=XOTO2qWRy9U", image: "https://cdn2.coachmag.co.uk/sites/coachmag/files/styles/insert_main_wide_image/public/2017/10/dumbbell-jump-squat.jpg?itok=_M4H3hL5")
walking_m = Workout.create(name: "Walking", description: "Walking is a convenient and an easy way for beginners to start exercising without feeling overwhelmed or needing to purchase equipment. Also, it’s a lower-impact exercise, meaning it doesn’t stress your joints. You can gradually increase the duration or frequency of your walks as you become more fit.", detail: "im to walk for 30 minutes, 3-4 times a week.", video: "https://www.youtube.com/watch?v=3Ka7B3hCg08&t=215s", image: "https://images.wsj.net/im-176247?width=1280&size=1")
jogging_m = Workout.create(name: "Jogging ", description: "Jogging is a great exercise to stay in shape. Jogging helps build strong bones, strengthen muscles and improve cardiovascular fitness. If you find jogging outdoors to be hard on your joints, try jogging on softer surfaces like grass. Also, many treadmills have built-in cushioning, which may be easier on your joints.", detail: "Aim to jog for 45-60 minutes, 3-4 times per week.", video: "https://www.youtube.com/watch?v=brFHyOtTwH4", image: "https://cdn.cdnparenting.com/articles/2019/01/21120025/1195922569-H.jpg")
cycling_m = Workout.create(name: "Cycling", description: "Cycling is a great exercise to stay in shape and great for people of all fitness levels, which can be done outdoors on a bicycle or indoors on a stationary bike. It has been linked to various health benefits, including increased insulin sensitivity and a reduced risk of certain chronic diseases.", detail: "Aim to cycle for 30 -60 minutes, 4-6 times per week at a moderate speed level.", video: "tps://www.youtube.com/watch?v=x4WHeVf5DN4", image: "https://static.euronews.com/articles/stories/04/96/92/54/945x531_cmsv2_46d24b9b-1eec-58cf-ad75-cc31ea0a204d-4969254.jpg")
yoga = Workout.create(name: "Yoga", description: "Yoga is a gentle way to stay in shape. It improves your posture, balance, and coordination. Yoga is a systematic practice of physical exercise, breath control, relaxation, diet control and positive thinking and meditation aimed at developing harmony in the body, mind, and environment.", detail: "Aim to workout 45-60 minutes, 4 times a week", video: "https://www.youtube.com/watch?v=SHdwAsUtRBg", image: "https://www.greenqueen.com.hk/wp-content/uploads/2019/11/Yoga-hip-CDN-.jpg")













weightloss = Goal.create(name: "Weight Loss", diet_id: keto.id)
muscle = Goal.create(name: "Muscle Gain", diet_id: protein.id)
endurance = Goal.create(name: "Endurance", diet_id: plant.id)
strength = Goal.create(name: "Strength",  diet_id: paleo.id)
maintainence = Goal.create(name: "Maintenance",  diet_id: clean.id)


a = GoalWorkout.create(goal_id: weightloss.id, workout_id: walking.id)
b = GoalWorkout.create(goal_id: weightloss.id, workout_id: jogging.id)
c = GoalWorkout.create(goal_id: weightloss.id, workout_id: cycling.id)
d = GoalWorkout.create(goal_id: weightloss.id, workout_id: swimming.id)
e = GoalWorkout.create(goal_id: weightloss.id, workout_id: hiit.id)
f = GoalWorkout.create(goal_id: muscle.id, workout_id: bench_press.id)
g = GoalWorkout.create(goal_id: muscle.id, workout_id: lat_pull_down.id)
h = GoalWorkout.create(goal_id: muscle.id, workout_id: cable_cross_over.id)
i = GoalWorkout.create(goal_id: muscle.id, workout_id: rest.id)
j = GoalWorkout.create(goal_id: muscle.id, workout_id: cable_straigth_arm_pull_down.id)
k  = GoalWorkout.create(goal_id: muscle.id, workout_id: incline_dumbbell_shoulder_press.id)
l = GoalWorkout.create(goal_id: muscle.id, workout_id: prone_dumbbell_row.id)
m = GoalWorkout.create(goal_id: muscle.id, workout_id: back_squat.id)
n  = GoalWorkout.create(goal_id: muscle.id, workout_id: overhead_press.id)
o = GoalWorkout.create(goal_id: muscle.id, workout_id: leg_extension.id)
p  = GoalWorkout.create(goal_id: muscle.id, workout_id: hamstring_curl.id)
q  = GoalWorkout.create(goal_id: muscle.id, workout_id: seated_dumbbell_overhead.id)
r = GoalWorkout.create(goal_id: muscle.id, workout_id: seated_dumbbell_lateral.id)
s  = GoalWorkout.create(goal_id: muscle.id, workout_id: rest.id)
t = GoalWorkout.create(goal_id: muscle.id, workout_id: under_lat_pull_down.id)
u = GoalWorkout.create(goal_id: muscle.id, workout_id: seated_cable_row.id)
v = GoalWorkout.create(goal_id: muscle.id, workout_id: incline_dumbbell_curl.id)
w = GoalWorkout.create(goal_id: muscle.id, workout_id: cable_curl.id)
x = GoalWorkout.create(goal_id: muscle.id, workout_id: cable_press_down.id)
y  = GoalWorkout.create(goal_id: muscle.id, workout_id: drips.id)
z  = GoalWorkout.create(goal_id: muscle.id, workout_id: incline_bench.id)
aa = GoalWorkout.create(goal_id: muscle.id, workout_id: rest.id)
ab  = GoalWorkout.create(goal_id: muscle.id, workout_id: dumbbell_pull_over.id)
ac  = GoalWorkout.create(goal_id: muscle.id, workout_id: ez_bar.id)
ad  = GoalWorkout.create(goal_id: muscle.id, workout_id: dumbbell_lateral_raise.id)
ae = GoalWorkout.create(goal_id: muscle.id, workout_id: incline_flye.id)
af = GoalWorkout.create(goal_id: muscle.id, workout_id: push_up.id)
ag = GoalWorkout.create(goal_id: endurance.id, workout_id: hiit_e.id)
ah = GoalWorkout.create(goal_id: endurance.id, workout_id: uphill.id)
ai = GoalWorkout.create(goal_id: endurance.id, workout_id: swimming_e.id)
aj = GoalWorkout.create(goal_id: endurance.id, workout_id: rest.id) 
ak = GoalWorkout.create(goal_id: endurance.id, workout_id: long_distance.id)
al = GoalWorkout.create(goal_id: endurance.id, workout_id: heavy.id)
am = GoalWorkout.create(goal_id: endurance.id, workout_id: cycling_e.id)
an = GoalWorkout.create(goal_id: strength.id, workout_id: kettlebell_goblet_squat.id) 
ao = GoalWorkout.create(goal_id: strength.id, workout_id: back_squat_s.id) 
ap = GoalWorkout.create(goal_id: strength.id, workout_id: bulgarian_split_squat.id) 
aq = GoalWorkout.create(goal_id: strength.id, workout_id: snatch_grip_deadlift.id) 
ar = GoalWorkout.create(goal_id: strength.id, workout_id: kettlebell_swing.id) 
as = GoalWorkout.create(goal_id: strength.id, workout_id: kettlebell_sumo_deadlift.id) 
at = GoalWorkout.create(goal_id: strength.id, workout_id: deadlift_s.id) 
au = GoalWorkout.create(goal_id: strength.id, workout_id: rest.id) 
av = GoalWorkout.create(goal_id: strength.id, workout_id: romanian_deadlift.id) 
aw = GoalWorkout.create(goal_id: strength.id, workout_id: incline_bench_press_s.id) 
ax = GoalWorkout.create(goal_id: strength.id, workout_id: push_up_s.id) 
ay = GoalWorkout.create(goal_id: strength.id, workout_id: dumbbell_bench_press_s.id) 
az = GoalWorkout.create(goal_id: strength.id, workout_id: bench_press_s.id) 
ba = GoalWorkout.create(goal_id: strength.id, workout_id: diamond_push_up.id) 
bb = GoalWorkout.create(goal_id: strength.id, workout_id: front_squat_s.id) 
bc = GoalWorkout.create(goal_id: strength.id, workout_id: dumbbell_jump_squat.id) 
bd = GoalWorkout.create(goal_id: maintainence.id, workout_id: walking_m.id) 
be = GoalWorkout.create(goal_id: maintainence.id, workout_id: jogging_m.id) 
bf = GoalWorkout.create(goal_id: maintainence.id, workout_id: cycling_m.id) 
bg = GoalWorkout.create(goal_id: maintainence.id, workout_id: yoga.id) 



angela = User.create(username: "angie235", first_name: "Angela", last_name: "Torres", image: "https://vignette.wikia.nocookie.net/theoffice/images/b/b6/111423.jpg/revision/latest?cb=20101116030321",  age: 25, height: 6, weight: 130, gender: "6", activity: "6", password: "6", goal_id: weightloss.id)

joseph = User.create(username: "joey_tech", first_name: "Joseph", last_name: "Doe", image: "https://pbs.twimg.com/media/DAM0C36VwAA19DM.jpg:large",  age: 32, height: 6, weight: 165, gender: "6", activity: "6", password:"6", goal_id: muscle.id )


GoalDiet.create(user_id: angela.id, diet_id: protein.id, goal_id: weightloss.id) 
GoalDiet.create(user_id: joseph.id, diet_id: keto.id, goal_id: muscle.id)
