# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Diet.destroy_all 
User.destroy_all
Workout.destroy_all
Goal.destroy_all 


keto = Diet.create(name: "Ketogenic", description: "A Ketogenic lifestyle is a very low carb, high fat diet that shares many similarities with the Atkins and low carb diets. It involves drastically reducing carbohydrate intake and replacing it with fat. This reduction in carbs puts your body into a metabolic state called ketosis, which becomes a fat burning machine.", restriction: "No sugar and your daily intake of carbohydrates should be less than 50 grams a day ", calorie: 0 , water: 0 )
paleo = Diet.create(name: "Paleolithic", description: "A Paleolithic lifestyle is based upon the premise of consuming only those foods available during the Paleolithic era (also known as the Stone Age). People at this time were hunter-gatherers, meaning that all animals were hunted and plants were gathered from nature.", restriction: "Processed foods, sugar, soft drinks, grains, most dairy products, legumes, artificial sweeteners, vegetable oils, margarine and trans fats.", calorie: 0 , water: 0)
clean = Diet.create(name: "Low Fat", description: "A Low Fat lifestyle is one that restricts fat, and often saturated fat and cholesterol as well. Low-fat diets are intended to reduce the occurrence of conditions such as heart disease and obesity. Fat carries a higher number of calories per gram than carbohydrates or proteins and so reducing fat can help to reduce your overall calorie intake. Whole grain versions of foods such as bread are recommended in preference to non-whole grain versions (such as white bread) partly because they are turned into blood sugar more slowly. The fibre and extra nutrients they contain are also healthier than white versions. It is recommended to include a significant proportion of fruit and vegetables through each day.", restriction: " Limit saturated fat to less than 7% of your total daily calories. Avoid trans fat as much as possible, which is typically used in fried and baked foods. ", calorie: 0 , water: 0 )
plant = Diet.create(name: "Plant Based", description: "A Plant-Based or Plant-Forward eating pattern focuses on foods primarily from plants. This includes not only fruits and vegetables, but also nuts, seeds, oils, whole grains, legumes, and beans. It doesn’t mean that you are vegetarian or vegan and never eat meat or dairy. Rather, you are proportionately choosing more of your foods from plant sources.", restriction: "Try to avoid fast food, desserts and sweetened beverages, packaged foods and processed meats.", calorie: 0 , water: 0 )
protein = Diet.create(name: "High Protein", description: "A High-Protein lifestyle encourages eating more protein and fewer carbohydrates or fat to boost weight loss, improve energy, and enhance athletic performance. Protein is an essential nutrient for health and is responsible for a number of important functions in the body, including hormones, enzymes, and cell repair and maintenance. In general, a high-protein diet recommends getting more than 20% of your total calories from protein.", restriction: "Eat less refined carbohydrates, such as bread, pasta and white rice, saturated fats and sugar.", calorie: 0 , water: 0)


cycling = Workout.create(name: "Cycling", description: "Biking is a top-notch cardio workout. It'll strengthens your lower body, including your legs, hips, and glutes. If you want a workout that’s gentle on your back, hips, knees, and ankles, this is a great choice.", detail: "30-60 minutes/workout for 2-3 days/week", video: "", image: " " )
running = Workout.create(name: "Running", description: "Running is a form of cardio exercise that's easily accessible. It is one of the most straightforward ways to get the important benefits of exercise. Since it improves aerobic fitness, running is a great way to help improve cardiovascular health.", detail: "45 - 60 minutes/workout", video: " ", image: " ")
weight  = Workout.create(name: "Weight Lifting", description: "Weight training is a common type of strength training for developing the strength and size of skeletal muscles. It utilizes the force of gravity in the form of weighted bars, dumbbells or weight stacks in order to oppose the force generated by muscle through concentric or eccentric contraction.", detail: "Beginners: 3-4 days/week Advanced: 4-6 days/week", video: "", image: " " )
hiit = Workout.create(name: "High-Intensity Interval Training (HIIT)", description: "High-intensity interval training, also called high-intensity intermittent exercise or sprint interval training, is a form of interval training, a cardiovascular exercise strategy alternating short periods of intense anaerobic exercise with less intense recovery periods, until too exhausted to continue.", detail: "2-3 days/week", video: " ", image: " ")
yoga = Workout.create(name: "Yoga", description: "Yoga is a mind and body practice with a 5,000-year history in ancient Indian philosophy. Various styles of yoga combine physical postures, breathing techniques, and meditation or relaxation.", detail: "30-60 minutes/session for 2-3 days/week", video: "", image: "")
swimming = Workout.create(name: "Swimming", description: "Swimming is an aerobic physical activity that is a good all-round activity that keeps your heart rate up but takes some of the impact stress off your body.", detail: "", video: "", image: "")
jiujitsu = Workout.create(name: "Jiu Jitsu", description: "", detail: "", video: "", image: "")
basketball = Workout.create(name: " Basketball", description: "", detail: "", video: "", image: "")
walking = Workout.create(name: "Walking", description: "", detail: "", video: "", image: "")
dancing = Workout.create(name: "Dancing", description: "", detail: "", video: "", image: "")

fatloss = Goal.create(name: "Fat Loss", workout_id: cycling.id, diet_id: keto.id)
muscle = Goal.create(name: "Muscle Gain", workout_id: weight.id, diet_id: paleo.id)
endurance = Goal.create(name: "Endurance", workout_id: running.id, diet_id: plant.id)
strength = Goal.create(name: "Strength", workout_id: weight.id, diet_id: protein.id)
maintainence = Goal.create(name: "Maintenance", workout_id: swimming.id, diet_id: clean.id)
self_defense = Goal.create(name: "Self Defense", workout_id: jiujitsu.id, diet_id: clean.id)


# fatloss = Goal.create(name: "Fat Loss", workout_id_1: cycling.id, workout_id_2: running.id, workout_id_3: weight.id, workout_id_4: hiit.id, workout_id_5: yoga.id, workout_id_6: swimming.id, workout_id_7: jiujitsu.id, workout_id_8: basketball.id, workout_id_9: walking.id, workout_id_10: dancing.id, diet_id: keto.id)

angela = User.create(username: "angie235", first_name: "Angela", last_name: "Torres", image: "https://vignette.wikia.nocookie.net/theoffice/images/b/b6/111423.jpg/revision/latest?cb=20101116030321",  age: 25, height: 6, weight: 130, gender: "6", activity: "6", password: "6", goal_id: fatloss.id)

joseph = User.create(username: "joey_tech", first_name: "Joseph", last_name: "Doe", image: "https://pbs.twimg.com/media/DAM0C36VwAA19DM.jpg:large",  age: 32, height: 6, weight: 165, gender: "6", activity: "6", password:"6", goal_id: muscle.id )


GoalDiet.create(user_id: angela.id, diet_id: protein.id, goal_id: fatloss.id) 
GoalDiet.create(user_id: joseph.id, diet_id: keto.id, goal_id: muscle.id)
